### PR TITLE
Remove entities from current

### LINKED ISSUE #1: Better filtering
I have seen a few anomalies in the currency data created by this script.

## Problem
  - Countries in the source without a currency get added to the list with a blank array key, with the last country in the list overwriting all previous countries: https://github.com/moneyphp/iso-currencies/blob/master/resources/current.php#L58
  - Handling of `EUR`, `USD` and other currencies used by multiple countries. There are multiple countries in the list each claiming usage of `EUR` (as is expected). In the generated output however, these get overwritten similarly to the above issue with the last country claiming the EUR 'winning' in the list, in the current iteration, Spain: https://github.com/moneyphp/iso-currencies/blob/master/resources/current.php#L10
(The USD is also affected: https://github.com/moneyphp/iso-currencies/blob/master/resources/current.php#L34)

## Possible Solutions
  - Do not process entries from the source without a valid currency code. This solves the first problem.
  - Do not include country data. As the current implementations in [\Money\Currencies\ISOCurrencies](https://github.com/moneyphp/money/blob/master/src/Currencies/ISOCurrencies.php) does not use country data, this is an easy option. Alternatively;
  - Store country data separately. (Can a use case be made for it?)

### PR DESCRIPTION
**Pull request by frederikbosch**
Fixes #1.

### CODE REVIEW

**Comment by frederikbosch** [comment]
@MichaelGooden Please tell me what you think.

@sagikazarmark As this will eventually also involve `Money`, please tell me if this can have your approval.

**Comment by sagikazarmark** [comment]
Why do we need country data in the first place? Do we use it at all? Also, what is "Ex" in the class names? Not really meaningful IMO.

**Comment by frederikbosch** [comment]
I am using Ex to say Excluding, will change it (without Ex). We do not need country data per se, but it is included in the original source. So for the sake of this package, I created multiple data files. With this PR you get a `current.php`, `current.json`, `current.with.entities.php` and a `current.with.entities.json`.

In Money we are (and will continue to) only embedding `current.php`.

**Comment by sagikazarmark** [comment]
Well, the package says iso currencies, so not sure if having such data included has any added value. But ok for me.

**Comment by MichaelGooden** [comment]
I vote against including the entities. As Mark says, this is a specialised
package, let's leave country data to packages which serve that function
better.

**Comment by frederikbosch** [comment]
@MichaelGooden @sagikazarmark Thanks for the feedback. As I do not care about those entities too, I have removed them. And merged it in.

**Comment by frederikbosch** [comment]
And since this is a BC break, I released it as 2.0.0.

**Pull request merged**
