### PR TITLE
Created a way to export the currencies to Yaml format using the symfony Yaml component

### LINKED ISSUE #5: Export to Yaml
Would you be interested in a MR that will implement the export of the Iso Currencies to a Yaml file using the symfony component?

### PR DESCRIPTION
**Pull request by gmponos**
closes #5

### CODE REVIEW

**Comment by frederikbosch** [comment]
Thanks! Merged and tagged.

**Comment by vukanac** [comment]
This potentially creates conflicts with project requirements that uses Symfony YAML component v^4.0.

**Comment by frederikbosch** [comment]
Why? Iso currencies is only a dev dependency of money. But, when you create a PR we can solve this.

**Comment by vukanac** [comment]
In the project I am updating, this package was used as required dependency and conflict arise about YAML version - unable to use v4.0.

Anyway, we liked the concept of this lib, but we missed this note:
"_Please be aware that this library solely exists to provide iso currencies for `moneyphp/money`. Using this library for other purposes is at your own risk._"

Now we have all resolved.
Thank you.

**Comment by frederikbosch** [comment]
I am nonetheless interested in a PR. Would you be willing to do the upgrade to version 4 of symfony/yaml?

**Pull request merged**
